name: contador24s_utm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.1

# --- ESTO ERA LO QUE FALTABA ---
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icono.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/icono.png"
# -------------------------------

flutter:
  uses-material-design: true
  assets:
    - assets/images/icono.png
    - assets/images/fondo.png